version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: author
      - name: rating
      - name: work
  - name: stg
    schema: stg
    tables:
      - name: author
      - name: rating
      - name: subject_people
      - name: subject_place
      - name: subject_time
      - name: subject
      - name: work_author
      - name: work

models:
  - name: author
    description: "Staging table for author data."
    columns:
      - name: id
        description: "Unique author id."
        tests:
          - unique
          - not_null
      - name: birth_date
        description: "Birth date of author"   
      - name: name
        description: "Name of author."
      - name: title
        description: "Title of author."
      - name: bio
        description: "Bio."
      - name: created
        description: "Date the entry was created."
      - name: last_modified
        description: "Date the entry was last modified."
        tests:
          - not_null

  - name: rating
    description: "Staging table for rating data."
    columns:
      - name: work_id
        description: "Work ID"
        tests:
          - not_null
      - name: average
        description: "Average"
      - name: count
        description: "Count"
        tests:
          - not_null
      - name: rating_1
        description: "Rating 1"
        tests:
          - not_null
      - name: rating_2
        description: "Rating 2"
        tests:
          - not_null
      - name: rating_3
        description: "Rating 3"
        tests:
          - not_null
      - name: rating_4
        description: "Rating 4"
        tests:
          - not_null
      - name: rating_5
        description: "Rating 5"
        tests:
          - not_null

  - name: work
    description: "Staging table for work data."
    columns:
      - name: id
        description: "Unique work id"
        tests:
          - not_null
      - name: title
        description: "Title of the work"
        tests:
          - not_null
      - name: description
        description: "Description"
      - name: created
        description: "Date the entry was created."
        tests:
          - not_null
      - name: last_modified
        description: "Date the entry was last modified."
        tests:
          - not_null

  - name: work_author
    description: "Bridge table between author and work"
    columns:
      - name: work_id
        description: "Work ID"
        tests:
          - not_null
      - name: author_id
        description: "Author ID"
        tests:
          - not_null

  - name: subject_place
    description: "Subject places"
    columns:
      - name: work_id
        description: "Work ID"
        tests:
          - not_null
      - name: subject_place
        description: "Subject place"
        tests:
          - not_null

  - name: subject
    description: "Subject"
    columns:
      - name: work_id
        description: "Work ID"
        tests:
          - not_null
      - name: subject
        description: "Subject"
        tests:
          - not_null

  - name: subject_time
    description: "Subject time"
    columns:
      - name: work_id
        description: "Work ID"
        tests:
          - not_null
      - name: subject_time
        description: "Subject time"
        tests:
          - not_null

  - name: subject_people
    description: "Subject people"
    columns:
      - name: work_id
        description: "Work ID"
        tests:
          - not_null
      - name: subject_people
        description: "Subject people"
        tests:
          - not_null