transform:
  outputs:
    dev:
      type: duckdb
      path: /Users/maryletteroa/Documents/Projects/DE/books/data/books.duckdb
      threads: 1

    prod:
      type: duckdb
      path: prod.duckdb
      threads: 4

  target: dev
